### ISSUE TITLE
Underdeveloped Paleontology/Anthropology/Archeology Section.

### ISSUE THREAD

**Issue by pennylessz** [PrejudiceNeutrino/YouTube_Channels#2]
These channels are very interesting and there is a ton of them. I wish someone would compile the ones that are actually well thought out and fact filled. This list is missing The Budget Museum, Animal Origins, Your Dinosaurs Are Wrong, Trey the Explainer, and Past Eon Productions. There are many more beyond this that I'm not aware of, but the point is that this portion of the list has a gaping hole.

P.S. NationSquid is unrelated, but I find his content very educational for tech and software history, please add him to a category if you find yourself agreeing upon viewing his content.

**Comment by PrejudiceNeutrino** [comment]
Sorry for the late reply, just got back from vacation. Thanks for all the recommendations, just added a paleontology/anthropology section to the list!
